const fs = require('fs');
let code = fs.readFileSync('src/Constructor.vue', 'utf8');

// 1. Remove the separate 'tariff' button from main view
code = code.replace(/<button class="smenu-nav-item" @click="openSidebarView\('tariff'\)">[\s\S]*?<\/button>/, '');

// 2. Rename the payment button text to "Способы оплаты и Тариф"
code = code.replace(/<button class="smenu-nav-item" @click="openSidebarView\('payment'\)">\s*<CreditCard :size="18" \/>\s*<span>.*?<\/span>\s*<\/button>/, 
`<button class="smenu-nav-item" @click="openSidebarView('payment')">
                <CreditCard :size="18" />
                <span>Оплата и Подписка</span>
              </button>`);

// 3. Update the payment view header text if any (optional, but it's generated by sidebarTitle)
code = code.replace(/payment: '.*?',/, "payment: 'Оплата и Подписка',");

// 4. Inject <MyTariffContent /> into the payment view
const paymentViewEndRegex = /(<template v-else-if="sidebarView === 'payment'">[\s\S]*?<\/label>\s*<\/div>\s*)(<\/div>\s*<\/template>)/;
code = code.replace(paymentViewEndRegex, `$1
              <div class="smenu-divider" style="margin: 20px 0; border-bottom: 1px solid #e5e7eb;"></div>
              
              <MyTariffContent />
            $2`);

// 5. Remove the standalone 'tariff' template view
code = code.replace(/<!-- 💳 TARIFF VIEW 💳 -->[\s\S]*?<template v-else-if="sidebarView === 'tariff'">[\s\S]*?<\/template>/, '');

fs.writeFileSync('src/Constructor.vue', code);
console.log('Merged payment and tariff views in Constructor.vue');

